### ISSUE TITLE
Garden fieldsettings should have a lastGroupingStep option

### ISSUE THREAD

**Issue by jaysencpp** [equinor/fusion-workspace#142]
## Expected Behavior

A garden's fieldsettings should have an optional property called `lastStep` which should be set to true if this specific grouping should be the last, and no other grouping is allowed after it.
## Current Behavior

A user can now group on everything without any constraint which might cause errors. For example in the app Heat Trace, the user should not be allowed to add any more groupings after HT Cable is chosen.
## Possible Solution

[Here](https://github.com/equinor/lighthouse-client/pull/1096)

**Comment by Gustav-Eikaas** [comment]
Closed due to serverside migration
