### ISSUE TITLE
GardenConfig type mismatch

### ISSUE THREAD

**Issue by jaysencpp** [equinor/fusion-workspace#164]
## Description
The type `GardenConfig` from workspace-fusion and the type from  createFusionWorkspace(..., .addGarden()) are not the same.
See https://github.com/equinor/fusion-workspace/blob/main/packages/workspace-fusion/src/lib/classes/fusionWorkspaceBuilder.tsx#L144

**Comment by Gustav-Eikaas** [comment]
@jaysencpp is this closed?

**Comment by jaysencpp** [comment]
Yes
