### ISSUE TITLE
HMR breaking application

### ISSUE THREAD

**Issue by GustavEikaas** [equinor/fusion-workspace#263]
Hot module replacement causes the workspace to crash for the following reason. Duplicate tab and viewController.destroy is not a function. The reason for this is that the configuration of tabs is not idiomatic.

**Comment by GustavEikaas** [comment]
Also seems to be breaking subscriptions

**Comment by Gustav-Eikaas** [comment]
![image](https://user-images.githubusercontent.com/89254170/210999743-3d511f8d-4b58-45f7-b8c9-e010c30cdf16.png)

**Comment by Gustav-Eikaas** [comment]
Making some sort of snapshot provider would allow the tabs to write their last state before unmounting, thus storing it while being unmounted.

**Comment by Gustav-Eikaas** [comment]
I believe something like this would fix HMR
