### ISSUE TITLE
ReactGrid not displaying vertical scrollbar when overflowing

### ISSUE THREAD

**Issue by jaysencpp** [equinor/fusion-workspace#328]
# Description
When ReactGrid is overflowing, there is no vertical scrollbar showing up. It's also not possible to scroll with scrollwheel.
Seems like this bump of ag-grid might be the cause: https://github.com/equinor/fusion-workspace/pull/255
Version 0.3.4 of workspace-ag-grid works as expected, but the later versions removes the vertical scrollbar.

**Comment by MagnusGjosund** [comment]
Too old issue
