### ISSUE TITLE
ReactGrid's gridOptions not applying

### ISSUE THREAD

**Issue by jaysencpp** [equinor/fusion-workspace#329]
# Description
Trying to pass gridOptions props to `ReactGrid` does not seem to apply.
```tsx
  <ReactGrid
      rowData={packages}
      colDefs={columns}
      height={500}
      gridOptions={{
        rowHeight: 200,
      }}
    />
```
Will look like this:
![image](https://user-images.githubusercontent.com/28650210/220632596-879e2630-8502-455f-8391-823ab280e46f.png)
I would expect each row to be 200px in height, but it will be 32px

**Comment by Gustav-Eikaas** [comment]
Rowheight is one of the few properties that can't be changed, do you have a use-case?
