### ISSUE TITLE
Opening EDS dropdowns (Quickfilters) will cause a "flicker render"

### ISSUE THREAD

**Issue by jaysencpp** [equinor/fusion-workspace#331]
# Description
When opening a quickfilter, the dropdown component will first appear to the top left of the screen for a very small amount of time, and then correctly place itself underneath the filter.

# Expected 
When opening a quickfilter, the component should not cause this "flicker render", and position itself correctly on first render.

**Comment by Gustav-Eikaas** [comment]
Look at this
