### ISSUE TITLE
Gantt research

### ISSUE THREAD

**Issue by ken-mellem** [equinor/fusion-workspace#350]
Investigations about which Gantt implementation we should go for; off the shelf or homebuilt.

**Comment by ken-mellem** [comment]
Meeting booked 06.03.2023

**Comment by Gustav-Eikaas** [comment]
Conclusion done;
When the time is right buying an off the shelf component is the way to go. 
Coding it from scratch is not feasible (cost wise)
Sufficient open source component is non existant.
