### ISSUE TITLE
Auto-size table columns

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/fusion-workspace#385]
All tables should be "auto-sized", except for description fields which should be default max XX chars.

This also covers the issues
- [x] equinor/cc-components#269
- [x] equinor/cc-components#266

**Comment by ken-mellem** [comment]
@MagnusGjosund are all columns now behaving similarly, auto-sizing appropriately? I would appreciate linking PRs to the issue it closes. That way you don't have to close the issue manually - and we have an audit trail ;)

So - I ask if this one can be closed?
