### ISSUE TITLE
chore: new menu for workspace should only have 5 px spacing

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/fusion-workspace#386]
new menu for workspace should only have 5 px spacing

**Comment by MagnusGjosund** [comment]
![Image](https://user-images.githubusercontent.com/54101675/234006936-a14e0378-d265-44c7-a2fe-d0d247573861.png)

**Comment by Gustav-Eikaas** [comment]
@MagnusGjosund You could probably look at this aswell

**Comment by AreWiv** [comment]
@MagnusGjosund How/where du I test?

**Comment by MagnusGjosund** [comment]
You can try to test this by using the developer tool in the browser. Then you can compare test and prod and see how many pixel the spacing are. If you need help call me on teams 😉

**Comment by MagnusGjosund** [comment]
@AreWiv You can test again now

**Comment by MagnusGjosund** [comment]
It's only in Loop and Punch
