### ISSUE TITLE
PowerApps in Workspace

### ISSUE THREAD

**Issue by JoneUE** [equinor/fusion-workspace#410]
Add option of embedding powerApps in as a workspace component

https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/embed-apps-dev

**Comment by Gustav-Eikaas** [comment]
Would be nice if we could figure out a way to prevent iframe embedding

**Comment by JoneUE** [comment]
Don't know any other way of embedding a PowerApp. How is it done for PBI?

**Comment by ken-mellem** [comment]
Can you add some information regarding the value and importance of this.

**Comment by JoneUE** [comment]
It will help OGP keep track of all the Safety barriers on the facility. It's been a high focus from OGP and is something they really want

**Comment by Gustav-Eikaas** [comment]
There is a project safety barriers report now, does that relieve this task?

**Comment by ken-mellem** [comment]
Closed for now.
