### ISSUE TITLE
Implement outside click for garden popover

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/fusion-workspace#424]
![image](https://github.com/equinor/fusion-workspace/assets/89254170/584b5228-e066-4c69-9b3b-de2fe6498d8d)
Doesnt close unless pressing the x button

Expected behaviour: The popover should close when clicking outside the popover

**Comment by Gustav-Eikaas** [comment]
You could probably fix this aswell @MagnusGjosund. Im pretty sure EDS have a useOutsideClick. Otherwise look through lighthouse-client

**Comment by MagnusGjosund** [comment]
This was a complicated task, then i got a lot of mergeconflicts i had a hard time to resolve. Need a break from this task. We should mabye just create a new branch and start all over. I didn't write a lot of code. The hard work was some technical things and some logic

**Comment by MagnusGjosund** [comment]
Made a new issue to start all over again #457

**Comment by MagnusGjosund** [comment]
Solved in this pr #458
