### ISSUE TITLE
Tooltip blank for all filter items

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/fusion-workspace#432]
![image](https://github.com/equinor/fusion-workspace/assets/89254170/65a4b221-86f9-4abb-b289-89a184d2ab2f)

**Comment by AreWiv** [comment]
Is this valid for all apps?
Any filter options that are not blank - for testing?

**Comment by MagnusGjosund** [comment]
This should be valid for all apps. There should not be any "blank", unless the filteroption is named "blank". 
Here is a better description https://github.com/equinor/fusion-workspace/pull/439

**Comment by AreWiv** [comment]
Tested and verified.
Comment: What is the value of a hover only stating the value you are hovering over - except when value is too long in the screen?

**Comment by MagnusGjosund** [comment]
I dont think the value can be too long. Do you have a case where this happens?
