### ISSUE TITLE
Tooltip on quick filters, and expandable quick filters

### ISSUE THREAD

**Issue by idrisbo** [equinor/fusion-workspace#452]
Currently, only (blank) is displayed on the tooltip when you hover over quick filters. The tooltip should instead display the label of the hovered quick filter.

The quick filter window should also be resizable.

![bilde](https://github.com/equinor/fusion-workspace/assets/112471345/ef369248-12a4-4a60-903e-d2ea2a0d5722)

(Expanded filter tooltip(how it should be)):
![bilde (1)](https://github.com/equinor/fusion-workspace/assets/112471345/c53ee07d-92be-4d9f-82bd-f91a1ae315de)

**Comment by ken-mellem** [comment]
@idrisbo appears this is already in PROD?

**Comment by MagnusGjosund** [comment]
@ken-mellem Are you sure you not are looking at expanded filters, and not quick filters?

**Comment by ken-mellem** [comment]
I updated with "How to test".
