### ISSUE TITLE
🎁 Enhancement: Garden column title must include Group by id

### ISSUE THREAD

**Issue by ken-mellem** [equinor/fusion-workspace#473]
In JC Portal
![image](https://github.com/equinor/fusion-workspace/assets/110427825/cd57705a-80f6-482d-a409-09e0d8f632a3)

Currently in Project Portal
![image](https://github.com/equinor/fusion-workspace/assets/110427825/c83cdf50-0520-4bbb-ac28-d5a409b4942c)

I have no visual information about what I have grouped by.

## Wanted outcome

In Garden view, decorate the column title to show some aggregation similar to that in JC Portal.

**Comment by ken-mellem** [comment]
@Gustav-Eikaas FYI. This became visible when @espenkalle pushed Handover to PROD.

**Comment by atlewee** [comment]
This can be closed as groupBy is now visible on right panel.
