### ISSUE TITLE
🎁: Garden column width option

### ISSUE THREAD

**Issue by espenkalle** [equinor/fusion-workspace#482]
## Expected outcome

Apps should be able to provide their own "garden column width" 

## Business Value / Developer Experience

Today all apps have the same "default" column width. Looks quite ugly in certain cases

## Acceptance Criteria

Garden items in different apps, for different contexts, should be visible and look nice :) No clipping, show entire number etc.

**Comment by Gustav-Eikaas** [comment]
@espenkalle Can this be closed? You forgot to link PR
