### ISSUE TITLE
🐛: Grouping Error

### ISSUE THREAD

**Issue by espenkalle** [equinor/fusion-workspace#515]
## Description
TypeError: Cannot destructure property 'isLoading' of 'n' as it is undefined.

![image](https://github.com/equinor/fusion-workspace/assets/108390105/8d467ae2-5adf-4809-871a-38e196474a31)

## Reproduce

1. Group by x then group by y.
2. Open a group. 
3. When "Then group by" is changed/cleared it breaks

![image](https://github.com/equinor/fusion-workspace/assets/108390105/8003399c-d273-4074-947d-e439cd692ad1)

**Comment by JoneUE** [comment]
#504
