### ISSUE TITLE
🎁: Show that there exist more than quick-filters

### ISSUE THREAD

**Issue by atlewee** [equinor/fusion-workspace#519]
## Expected outcome
If there is more filters in advanced mode than quickFilter, we should have some indication showing that more filters are available.
Also when a hidden filter is applied, that should be visible to the user.
JC-portal has information about this:
![image](https://github.com/equinor/fusion-workspace/assets/11732817/86fa739e-5373-4b28-8b9e-f9d618c8486c)
This is missing in project portal.

## Acceptance Criteria
- [x] User can see that more filters are available in advanced mode.
- [x] User can see if any advanced filters is active, also when advanced filter is hidden

**Comment by JoneUE** [comment]
Maybe something like this could work

![Image](https://github.com/equinor/fusion-workspace/assets/73601851/3a7ee70a-ee58-4d02-9fd7-09e6753ad266)
