### ISSUE TITLE
🐛: PBI wrapper - Access denied message is wrong

### ISSUE THREAD

**Issue by atlewee** [equinor/fusion-workspace#550]
## Description

If user does not have access to a report, the wrapper generates this error message, asking the user to try again.
![image](https://github.com/equinor/fusion-workspace/assets/11732817/47a9be8c-3681-4230-a4bd-2fb299ea98dc)

## Reproduce

Open a PowerBI report you do not have access to.

## Expected behavior

Error message saying you do not have access.

## Fusion Core reference
- https://statoil-proview.visualstudio.com/Fusion%20Core/_workitems/edit/47586

**Comment by Htonning** [comment]
In addition to making the error message more accurate, we also want the ability to customize the error message to explain users how they should get access. We have this functionality in the old fusion power bi wrapper.

**Comment by atlewee** [comment]
@Htonning  : That is covered by issue: #551

**Comment by Gustav-Eikaas** [comment]
@atlewee The error message showing comes from the fusion core legacy powerbi wrapper not from workspace.

**Comment by ken-mellem** [comment]
I have contacted Core Team Lead @EirikHovland.

**Comment by ken-mellem** [comment]
Updated with reference to Fusion Core https://statoil-proview.visualstudio.com/Fusion%20Core/_workitems/edit/47586.

**Comment by ken-mellem** [comment]
Keeping alive to track it.

**Comment by Htonning** [comment]
@ken-mellem  - Hans has asked for more information in the DevOps case. Can you or someone from your team provide more details?

**Comment by ken-mellem** [comment]
It should be mentioned in the OP that this is for the new fusion wrapper which we primarily use in the Project Portal - not the old Fusion PBI wrapper typically used in the Fusion portal. I suspect he is testing the wrong thing.
