### ISSUE TITLE
🐛: SWCR: double grouping

### ISSUE THREAD

**Issue by JoneUE** [equinor/fusion-workspace#598]
## Description

Seem to be a UX problem when grouping twice

![Image](https://github.com/equinor/fusion-workspace/assets/73601851/89b61923-309f-430d-87d6-140c3b2405de)

## Reproduce

Group twice

**Comment by Gustav-Eikaas** [comment]
This looks like its in Castberg? If so it doesnt use the code from this repo

**Comment by JoneUE** [comment]
This is in the new portal, I'm guessing the Worksapce haven't been updated to newest version

**Comment by Gustav-Eikaas** [comment]
Oh yeah, you are right. The swcr production build has not been replaced yet. I'm not sure how much time we should invest in fixing this. Maybe our efforts are better spent getting the new one production ready?

**Comment by EdwardBrunton** [comment]
Waiting for response from @JoneUE

**Comment by JoneUE** [comment]
It's better to get the new one production ready
