### ISSUE TITLE
🐛: Workspace: Filters dissapears when checking boxes

### ISSUE THREAD

**Issue by atlewee** [equinor/fusion-workspace#609]
## Description
When changing filters by checking the checkboxes, the filters now closes. (Should stay open)
Also a visual bug with green hover thing:
![image](https://github.com/equinor/fusion-workspace/assets/11732817/61669f95-654f-433a-81c0-2b64972e12a9)

## Reproduce
Open advances filter and turn off one checkbox:
![image](https://github.com/equinor/fusion-workspace/assets/11732817/6b9af70e-864a-40a2-aee7-986608c9bc40)

All filters are now closed>
![image](https://github.com/equinor/fusion-workspace/assets/11732817/b87d7daa-c2d3-4957-b8e1-44daa5025b5e)

## Expected behavior
Filter should stay open

**Comment by Gustav-Eikaas** [comment]
@kjellhaaland Is this related to the bumping of packages? Would you mind taking a look at this 🥇
