### ISSUE TITLE
🐛: AG-grid deprecation warnings

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/fusion-workspace#631]
## Description
Getting numerous console warnings on deprecated grid api function invocations after upgrading ag grid. Functionality seems to be working but this should be addressed.

`AG Grid: setColumnDefs is deprecated. Please use 'api.setGridOption('columnDefs', newValue)' or 'api.updateGridOptions({ columnDefs: newValue })' instead.`

`AG Grid: Since v31, 'columnApi.getAllDisplayedColumns' is deprecated and moved to 'api.getAllDisplayedColumns'.`

`AG Grid: Since v31, 'columnApi.autoSizeColumns' is deprecated and moved to 'api.autoSizeColumns'.`

## Repro

1. Enter Loop app
2. Go to grid tab
3. Check console

**Comment by kjellhaaland** [comment]
@EdwardBrunton can we close this?
